cart/urls.py
from django.urls import path
from . import views
from shop.views import add_review

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),

         

         
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'shop'
urlpatterns = [
    path('',views.product_list,name='product_list'),
    path('login/',views.loginuser,name='login'),
    path('logout/',views.logoutuser,name='logout'),
    path('register/',views.register, name='register'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('category/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('add_review/<int:product_id>/', views.add_review, name='add_review'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class User(AbstractUser):
    image = models.ImageField(upload_to='media/users_images',blank=True)
    phone_num = models.CharField(blank=True,max_length=30)
    
    class Meta:
        ordering = ('username',)
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    
    def __str__(self):
        return self.username


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    name = models.CharField(max_length=150, db_index=True)
    slug = models.CharField(max_length=150, db_index=True, unique=True)
    image = models.ImageField(upload_to='media/%Y/%m/%d', blank=True)
    description = models.TextField(max_length=1000, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    uploaded = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])
    
class Review(models.Model):
    RATING_CHOICES = (
        (1, '1 Star'),
        (2, '2 Stars'),
        (3, '3 Stars'),
        (4, '4 Stars'),
        (5, '5 Stars'),
    )

    product = models.ForeignKey('Product', related_name='reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    body = models.TextField()
    rating = models.IntegerField(choices=RATING_CHOICES, default=5)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

    def __str__(self):
        return f'{self.title} - {self.user.username}'

shop/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User , Review
class UserCreationFormByMe(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'image',
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
            'phone_num',

        ]


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            'title',
            'body',
            'rating'
        ]

    title = forms.CharField(label='Заголовок', max_length=255)
    body = forms.CharField(label='Текст отзыва', widget=forms.Textarea)
    rating = forms.ChoiceField(label='Рейтинг', choices=Review.RATING_CHOICES)

    

shop/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import login,logout,authenticate
from .models import User ,Product , Category,Review
from .forms import UserCreationFormByMe,ReviewForm
from django.contrib import messages
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required

def loginuser(request):
    # return render(request,'users/login.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('shop:product_list')
        else:
            # Обработка неправильных учетных данных
            return render(request, 'users/login.html', {'error': 'Invalid username or password.'})
    else:
        return render(request, 'users/login.html')

def logoutuser(request):
    logout(request)
    return redirect('shop:product_list')




def register(request):
    if request.method == 'GET':
        form  = UserCreationFormByMe()
        context = {'form': form}
        return render(request, 'users/register.html', context)
    if request.method == 'POST':
        form  = UserCreationFormByMe(request.POST)
    if form.is_valid():
        form.save()
        user = form.cleaned_data.get('username')
        messages.success(request, 'Account was created for ' + user)
        return redirect('shop:product_list')
    else:
        print('Form is not valid')
        messages.error(request, 'Error Processing Your Request')
        context = {'form': form}
        return render(request, 'users/register.html', context)
    return render(request, 'users/register.html', {})


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/home.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products
                  })




def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    reviews = Review.objects.filter(product=product)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/detail.html', {'product': product,'cart_product_form':cart_product_form,'reviews': reviews,})
    

@login_required  
def add_review(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.user = request.user
            review.save()
            return redirect('shop:product_detail', id=product.id, slug=product.slug)
    else:
        form = ReviewForm()

    return render(request, 'shop/add_review.html', {'form': form, 'product': product})

templates/shop/add_review.html
{% extends "shop/base.html" %}
{% block title %}
  Оставить отзыв
{% endblock %}
{% block content %}
  <h2>Оставить отзыв</h2>
  <form method="post" action="{% url 'shop:add_review' product.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить отзыв</button>
  </form>
  <a href="{% url 'shop:product_detail' product.id product.slug %}">Назад к продукту</a>
{% endblock %}

templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base  </title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <div id="header">
        <a href="/" class="logo">Pc Shop</a>
    </div>
    {% if user.is_authenticated %}
    <p>{{user.username}}</p>
    <a href="{% url 'shop:logout' %}">Logout</a>
{% else %}
    <a href="{% url 'shop:login' %}">Login</a>
    <a href="{% url 'shop:register' %}">Register</a>
{% endif %}
    
</head>
<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
        {% if cart|length > 0 %}
        На корзине:
        <a href="{% url 'cart:cart_detail' %}">
            {{ total_items }} штук , ${{ cart.get_total_price }}
        </a> 
        {% else %}
        Корзина пуста
        {% endif %}
        {% endwith %}

    </div>
</div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>

</html>

templates/shop/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
    {% if product.image %}
    <img src="{{ product.image.url }}" alt="Product Image">
{% endif %}
<h1>{{ product.name }}</h1>
<h2>
<a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
</h2>
<p class="price">${{ product.price }}</p>
<form action="{% url 'cart:cart_add' product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Добавить в корзинку">
    
</form>
{{ product.description|linebreaks }}
</div>


<!-- Отображение отзывов -->
<div class="reviews">
    <h2>Отзывы</h2>
    {% if reviews %}
        <ul>
            {% for review in reviews %}
                <li>
                    <strong>{{ review.user.username }}</strong> - {{ review.created_at|date:"d.m.Y" }}
                    <p>Рейтинг: {{ review.get_rating_display }}</p>
                    <p>{{ review.body }}</p>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Пока нет отзывов для этого продукта.</p>
    {% endif %}
</div>
{% endblock %}

templates/shop/home.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
<h3>Category</h3>
<ul>
<li {% if not category %}class="selected"{% endif %}>
<a href="{% url 'shop:product_list' %}">Barligi</a>
</li>
{% for c in categories %}
<li {% if category.slug == c.slug %}class="selected" {% endif %}>
<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
</li>
{% endfor %}
</ul>
</div>
<div id="main" class="product-list">
<h1>{% if category %}{{ category.name }}{% else %}Tovar{% endif %}</h1>
{% for product in products %}
<div class="item">
<a href="{{ product.get_absolute_url }}">
    <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static 'media/no_image.png' %}{% endif %}">
</a>
<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
<br>
${{ product.price }}
</div>
{% endfor %}
</div>
{% endblock %}